"""Remove redundant id

Revision ID: 06d0e29ebce7
Revises: cb437b94bf6e
Create Date: 2024-12-13 01:12:17.381359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "06d0e29ebce7"
down_revision: Union[str, None] = "cb437b94bf6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_paquetes_rechazados_data", table_name="paquetes_rechazados")
    op.drop_index("ix_paquetes_rechazados_date", table_name="paquetes_rechazados")
    op.drop_index("ix_paquetes_rechazados_motivo", table_name="paquetes_rechazados")
    op.drop_index("ix_paquetes_rechazados_nodo_id", table_name="paquetes_rechazados")
    op.drop_index("ix_paquetes_rechazados_type_id", table_name="paquetes_rechazados")
    op.drop_table("paquetes_rechazados")

    op.drop_index("ix_paquetes_archivo_data", table_name="paquetes_archivo")
    op.drop_index("ix_paquetes_archivo_date", table_name="paquetes_archivo")
    op.drop_index("ix_paquetes_archivo_id", table_name="paquetes_archivo")
    op.drop_index("ix_paquetes_archivo_nodo_id", table_name="paquetes_archivo")
    op.drop_table("paquetes_archivo")

    op.drop_constraint("paquetes_type_id_fkey", "paquetes", type_="foreignkey")
    op.drop_constraint("paquetes_nodo_id_fkey", "paquetes", type_="foreignkey")

    op.drop_index("ix_tipos_data_symbol", table_name="tipos")
    op.drop_index("ix_tipos_data_type", table_name="tipos")
    op.drop_index("ix_tipos_id", table_name="tipos")
    op.drop_index("ix_tipos_nombre", table_name="tipos")
    op.drop_table("tipos")

    op.drop_index("ix_paquetes_data", table_name="paquetes")
    op.drop_index("ix_paquetes_date", table_name="paquetes")
    op.drop_index("ix_paquetes_id", table_name="paquetes")
    op.drop_table("paquetes")

    op.add_column(
        "nodos",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "nodos", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_index("ix_nodos_id", table_name="nodos")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_nodos_id", "nodos", ["id"], unique=False)
    op.drop_column("nodos", "updated_at")
    op.drop_column("nodos", "created_at")

    op.create_table(
        "paquetes",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("nodo_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "data",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["nodo_id"], ["nodos.identificador"], name="paquetes_nodo_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["type_id"], ["tipos.data_type"], name="paquetes_type_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="paquetes_pkey"),
    )
    op.create_index("ix_paquetes_id", "paquetes", ["id"], unique=False)
    op.create_index("ix_paquetes_date", "paquetes", ["date"], unique=False)
    op.create_index("ix_paquetes_data", "paquetes", ["data"], unique=False)

    op.create_table(
        "tipos",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('tipos_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("data_type", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "data_symbol", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("nombre", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="tipos_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_tipos_nombre", "tipos", ["nombre"], unique=True)
    op.create_index("ix_tipos_id", "tipos", ["id"], unique=False)
    op.create_index("ix_tipos_data_type", "tipos", ["data_type"], unique=True)
    op.create_index("ix_tipos_data_symbol", "tipos", ["data_symbol"], unique=True)

    op.create_table(
        "paquetes_archivo",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "data",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("nodo_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["type_id"], ["tipos.data_type"], name="paquetes_archivo_type_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="paquetes_archivo_pkey"),
    )
    op.create_index(
        "ix_paquetes_archivo_nodo_id", "paquetes_archivo", ["nodo_id"], unique=False
    )
    op.create_index("ix_paquetes_archivo_id", "paquetes_archivo", ["id"], unique=False)
    op.create_index(
        "ix_paquetes_archivo_date", "paquetes_archivo", ["date"], unique=False
    )
    op.create_index(
        "ix_paquetes_archivo_data", "paquetes_archivo", ["data"], unique=False
    )

    op.create_table(
        "paquetes_rechazados",
        sa.Column("nodo_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("data", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("motivo", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("nodo_id", "date", name="paquetes_rechazados_pkey"),
    )
    op.create_index(
        "ix_paquetes_rechazados_type_id",
        "paquetes_rechazados",
        ["type_id"],
        unique=False,
    )
    op.create_index(
        "ix_paquetes_rechazados_nodo_id",
        "paquetes_rechazados",
        ["nodo_id"],
        unique=False,
    )
    op.create_index(
        "ix_paquetes_rechazados_motivo", "paquetes_rechazados", ["motivo"], unique=False
    )
    op.create_index(
        "ix_paquetes_rechazados_date", "paquetes_rechazados", ["date"], unique=False
    )
    op.create_index(
        "ix_paquetes_rechazados_data", "paquetes_rechazados", ["data"], unique=False
    )
    # ### end Alembic commands ###
