"""database

Revision ID: cb437b94bf6e
Revises: e8105b33fb1d
Create Date: 2024-12-12 19:10:49.162891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb437b94bf6e'
down_revision: Union[str, None] = 'e8105b33fb1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nueva_tabla_id', table_name='nueva_tabla')
    op.drop_table('nueva_tabla')
    op.drop_index('ix_paquetes_rechazados_data', table_name='paquetes_rechazados')
    op.drop_index('ix_paquetes_rechazados_date', table_name='paquetes_rechazados')
    op.drop_index('ix_paquetes_rechazados_motivo', table_name='paquetes_rechazados')
    op.drop_index('ix_paquetes_rechazados_nodo_id', table_name='paquetes_rechazados')
    op.drop_index('ix_paquetes_rechazados_type_id', table_name='paquetes_rechazados')
    op.drop_table('paquetes_rechazados')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paquetes_rechazados',
    sa.Column('nodo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('motivo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('nodo_id', 'date', name='paquetes_rechazados_pkey')
    )
    op.create_index('ix_paquetes_rechazados_type_id', 'paquetes_rechazados', ['type_id'], unique=False)
    op.create_index('ix_paquetes_rechazados_nodo_id', 'paquetes_rechazados', ['nodo_id'], unique=False)
    op.create_index('ix_paquetes_rechazados_motivo', 'paquetes_rechazados', ['motivo'], unique=False)
    op.create_index('ix_paquetes_rechazados_date', 'paquetes_rechazados', ['date'], unique=False)
    op.create_index('ix_paquetes_rechazados_data', 'paquetes_rechazados', ['data'], unique=False)
    op.create_table('nueva_tabla',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='nueva_tabla_pkey')
    )
    op.create_index('ix_nueva_tabla_id', 'nueva_tabla', ['id'], unique=False)
    # ### end Alembic commands ###
