"""Initial migration

Revision ID: e685290144f5
Revises: 
Create Date: 2024-12-12 04:18:40.158766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e685290144f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificador', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodos_descripcion'), 'nodos', ['descripcion'], unique=False)
    op.create_index(op.f('ix_nodos_id'), 'nodos', ['id'], unique=False)
    op.create_index(op.f('ix_nodos_identificador'), 'nodos', ['identificador'], unique=True)
    op.create_index(op.f('ix_nodos_is_active'), 'nodos', ['is_active'], unique=False)
    op.create_index(op.f('ix_nodos_latitud'), 'nodos', ['latitud'], unique=False)
    op.create_index(op.f('ix_nodos_longitud'), 'nodos', ['longitud'], unique=False)
    op.create_index(op.f('ix_nodos_nombre'), 'nodos', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodos_nombre'), table_name='nodos')
    op.drop_index(op.f('ix_nodos_longitud'), table_name='nodos')
    op.drop_index(op.f('ix_nodos_latitud'), table_name='nodos')
    op.drop_index(op.f('ix_nodos_is_active'), table_name='nodos')
    op.drop_index(op.f('ix_nodos_identificador'), table_name='nodos')
    op.drop_index(op.f('ix_nodos_id'), table_name='nodos')
    op.drop_index(op.f('ix_nodos_descripcion'), table_name='nodos')
    op.drop_table('nodos')
    # ### end Alembic commands ###
